package ca.gbc.comp3095.inventoryservice.repository;

import ca.gbc.comp3095.inventoryservice.model.Inventory;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * The InventoryRepository interface extends JpaRepository to provide basic CRUD operations
 * for the Inventory entity. JpaRepository is part of Spring Data JPA, which simplifies
 * the process of working with relational databases by generating queries from method names.
 */
public interface InventoryRepository extends JpaRepository<Inventory, Long> {

    /**
     * Custom query method generated by Spring Data JPA. Based on the method name, Spring Data JPA
     * automatically derives the appropriate SQL query to check if an inventory item with the given
     * SKU code exists and whether its quantity is greater than or equal to the specified amount.
     *
     * Method name breakdown:
     * - "existsBy": This tells Spring Data JPA that we're checking for the existence of records.
     * - "SkuCode": Refers to the 'skuCode' field in the Inventory entity, which will be matched
     *    against the provided 'skuCode' parameter.
     * - "AndQuantityGreaterThanEqual": This tells Spring Data JPA to also compare the 'quantity'
     *    field in the entity, ensuring it is greater than or equal to the provided 'quantity' parameter.
     *
     * Spring Data JPA will automatically translate this method into an SQL query that looks something like:
     *
     * SELECT CASE WHEN COUNT(i) > 0 THEN TRUE ELSE FALSE END
     * FROM t_inventory i
     * WHERE i.sku_code = ?1 AND i.quantity >= ?2;
     *
     * @param skuCode the SKU code of the inventory item.
     * @param quantity the minimum quantity required to determine if the item is in stock.
     * @return true if an item with the given SKU code exists and its quantity is greater than or equal to the given value, false otherwise.
     */
    boolean existsBySkuCodeAndQuantityGreaterThanEqual(String skuCode, Integer quantity);
}